name: module_github
description: A new Flutter project.
homepage: http://www.baidu.com
repository: https://www.baidu.com
version: 1.0.0
publish_to: http://localhost:8080

router: true
environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  service_finder:
    hosted:
      name: service_finder
      url: http://localhost:8080
    version: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
